# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "thunderbolt" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5f1cef9c-2446-4e25-a165-8cfb5bdefdb1";
      fsType = "btrfs";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/89238a71-a38f-4116-aa0c-195c2b6a821e";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/game" =
    { device = "/dev/disk/by-uuid/89238a71-a38f-4116-aa0c-195c2b6a821e";
      fsType = "btrfs";
      options = [ "subvol=@game" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E482-7BDE";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/5bb195ab-3320-433f-a384-2287a4f53079"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
