[general]
import = [
  "~/.config/alacritty/settings/general.toml",
  "~/.config/alacritty/settings/colorscheme.toml",
  "~/.config/alacritty/settings/fonts.toml",
  "~/.config/alacritty/settings/keybindings.toml",
  "~/.config/alacritty/settings/mouse.toml",
]
working_directory = "C:/Users/almag"
