# Autogenerated config.py
#
# NOTE: config.py is intended for advanced users who are comfortable
# with manually migrating the config file on qutebrowser upgrades. If
# you prefer, you can also configure qutebrowser using the
# :set/:bind/:config-* commands without having to write a config.py
# file.
#
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Change the argument to True to still load settings configured via autoconfig.yml
config.load_autoconfig(True)

# Aliases for commands. The keys of the given dictionary are the
# aliases, while the values are the commands they map to.
# Type: Dict
c.aliases = {
    "q": "close",
    "qa": "quit",
    "w": "session-save",
    "wq": "quit --save",
    "wqa": "quit --save",
    "re": "restart",
}

c.qt.force_software_rendering = 'chromium'
c.qt.force_platform = 'wayland'
c.auto_save.session = True

c.qt.args = [
    "enable-features=UseOzonePlatform",
    #"ozone-platform=wayland",
]

config.set("content.cookies.accept", "all", "chrome-devtools://*")
config.set("content.cookies.accept", "all", "devtools://*")
config.set("content.cookies.accept", "all", "https://www.sooplive.co.kr/*")
config.set("content.cookies.accept", "all", "https://play.sooplive.co.kr/*")

c.content.blocking.whitelist = [
    "https://www.sooplive.co.kr/*",
    "https://play.sooplive.co.kr/*",
]

# Value to send in the `Accept-Language` header. Note that the value
# read from JavaScript is always the global value.
# Type: String
c.content.headers.accept_language = 'ko-KR,en-US;q=0.8,en;q=0.7'

# Value to send in the `Accept-Language` header. Note that the value
# read from JavaScript is always the global value.
# Type: String
config.set('content.headers.accept_language', '', 'https://matchmaker.krunker.io/*')

config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version} (KHTML, like Gecko) {upstream_browser_key}/{upstream_browser_version} Safari/{webkit_version}', 'https://web.whatsapp.com/')
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}; rv:145.0) Gecko/20100101 Firefox/145.0', 'https://accounts.google.com/*')
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version} (KHTML, like Gecko) {qt_key}/{qt_version} {upstream_browser_key}/{upstream_browser_version_short} Safari/{webkit_version}', 'https://gitlab.gnome.org/*')

config.set('content.images', True, 'chrome-devtools://*')
config.set('content.images', True, 'devtools://*')
config.set('content.javascript.enabled', True, 'file://*')
config.set('content.javascript.enabled', True, 'https://www.sooplive.co.kr/*')
config.set('content.javascript.enabled', True, 'https://play.sooplive.co.kr/*')
config.set('content.javascript.enabled', True, 'chrome-devtools://*')
config.set('content.javascript.enabled', True, 'devtools://*')
config.set('content.javascript.enabled', True, 'chrome://*/*')
config.set('content.javascript.enabled', True, 'qute://*/*')
config.set('content.local_content_can_access_remote_urls', True, 'file:///home/almagest/.local/share/qutebrowser/userscripts/*')
config.set('content.local_content_can_access_file_urls', False, 'file:///home/almagest/.local/share/qutebrowser/userscripts/*')
config.set('content.notifications.enabled', True, 'https://laftel.net')
config.set('content.notifications.enabled', False, 'https://www.youtube.com')

# Page to open if :open -t/-b/-w is used without URL. Use `about:blank`
# for a blank page.
# Type: FuzzyUrl
c.url.default_page = 'https://duckduckgo.com'

c.url.searchengines = {
    "DEFAULT": "https://www.google.com.ar/search?q={}",
    "ar": "https://wiki.archlinux.org/index.php/{}",
    "yt": "https://www.youtube.com/results?search_query={}",
    "=": "https://www.wolframalpha.com/input/?i={}",
    "ct": "https://www.ctan.org/search?phrase={}",
    "lg": "http://gen.lib.rus.ec/search.php?req={}&lg_topic=libgen&open=0&view=simple&res=25&phrase=1&column=def",
    "ha": "https://hoogle.haskell.org/?hoogle={}",
}

#          ╭──────────────────────────────────────────────────────────╮
#          │                       Colorscheme                        │
#          ╰──────────────────────────────────────────────────────────╯
c.colors.completion.fg = "#a0b3c5"
c.colors.completion.odd.bg = "#171D22"
c.colors.completion.even.bg = "#1D252C"
c.colors.completion.category.fg = "#539AFC"
c.colors.completion.category.bg = "#171D22"
c.colors.completion.category.border.top = "#0F110C"
c.colors.completion.category.border.bottom = "#0F110C"
c.colors.completion.item.selected.fg = "#70E1E8"
c.colors.completion.item.selected.bg = "#10151C"
c.colors.completion.item.selected.border.top = "#10151C"
c.colors.completion.item.selected.border.bottom = "#10151C"
c.colors.completion.item.selected.match.fg = "#D98E48"
c.colors.completion.match.fg = "#EBBF83"
c.colors.completion.scrollbar.fg = "#a0b3c5"
c.colors.completion.scrollbar.bg = "#1D252C"
c.colors.contextmenu.menu.bg = "#1D252C"
c.colors.contextmenu.menu.fg = "#a0b3c5"
c.colors.contextmenu.selected.bg = "#10151C"
c.colors.contextmenu.selected.fg = "#a0b3c5"
c.colors.contextmenu.disabled.bg = "#171D22"
c.colors.contextmenu.disabled.fg = "#56697a"
c.colors.downloads.bar.bg = "#1D252C"
c.colors.downloads.start.fg = "#1D252C"
c.colors.downloads.start.bg = "#539AFC"
c.colors.downloads.stop.fg = "#1D252C"
c.colors.downloads.stop.bg = "#008b94"
c.colors.downloads.error.fg = "#d95468"
c.colors.hints.fg = "#1D252C"
c.colors.hints.bg = "#EBBF83"
c.colors.hints.match.fg = "#a0b3c5"
c.colors.keyhint.fg = "#a0b3c5"
c.colors.keyhint.suffix.fg = "#EBBF83"
c.colors.keyhint.bg = "#1D252C"
c.colors.messages.error.fg = "#d95468"
c.colors.messages.error.bg = "#1D252C"
c.colors.messages.error.border = "#d95468"
c.colors.messages.warning.fg = "#D98E48"
c.colors.messages.warning.bg = "#1D252C"
c.colors.messages.warning.border = "#D98E48"
c.colors.messages.info.fg = "#70E1E8"
c.colors.messages.info.bg = "#1D252C"
c.colors.messages.info.border = "#70E1E8"
c.colors.prompts.fg = "#a0b3c5"
c.colors.prompts.border = "#1D252C"
c.colors.prompts.bg = "#1D252C"
c.colors.prompts.selected.fg = "#a0b3c5"
c.colors.prompts.selected.bg = "#10151C"
c.colors.statusbar.normal.fg = "#8BD49C"
c.colors.statusbar.normal.bg = "#1D252C"
c.colors.statusbar.insert.fg = "#1D252C"
c.colors.statusbar.insert.bg = "#539AFC"
c.colors.statusbar.passthrough.fg = "#1D252C"
c.colors.statusbar.passthrough.bg = "#008b94"
c.colors.statusbar.private.fg = "#eadced"
c.colors.statusbar.private.bg = "#5e176b"
c.colors.statusbar.command.fg = "#a0b3c5"
c.colors.statusbar.command.bg = "#1D252C"
c.colors.statusbar.command.private.fg = "#eadced"
c.colors.statusbar.command.private.bg = "#5e176b"
c.colors.statusbar.caret.fg = "#1D252C"
c.colors.statusbar.caret.bg = "#b62d65"
c.colors.statusbar.caret.selection.fg = "#1D252C"
c.colors.statusbar.caret.selection.bg = "#539AFC"
c.colors.statusbar.progress.bg = "#539AFC"
c.colors.statusbar.url.fg = "#a0b3c5"
c.colors.statusbar.url.error.fg = "#d95468"
c.colors.statusbar.url.hover.fg = "#70E1E8"
c.colors.statusbar.url.success.http.fg = "#a0b3c5"
c.colors.statusbar.url.success.https.fg = "#8BD49C"
c.colors.statusbar.url.warn.fg = "#e27e8d"
c.colors.tabs.bar.bg = "#1D252C"
c.colors.tabs.indicator.start = "#539AFC"
c.colors.tabs.indicator.stop = "#008b94"
c.colors.tabs.indicator.error = "#d95468"
c.colors.tabs.odd.fg = "#a0b3c5"
c.colors.tabs.odd.bg = "#10151C"
c.colors.tabs.even.fg = "#a0b3c5"
c.colors.tabs.even.bg = "#10151C"
c.colors.tabs.selected.odd.fg = "#a0b3c5"
c.colors.tabs.selected.odd.bg = "#41505e"
c.colors.tabs.selected.even.fg = "#a0b3c5"
c.colors.tabs.selected.even.bg = "#41505e"
c.colors.tabs.pinned.odd.fg = "#a0b3c5"
c.colors.tabs.pinned.odd.bg = "#10151C"
c.colors.tabs.pinned.even.fg = "#a0b3c5"
c.colors.tabs.pinned.even.bg = "#10151C"
c.colors.tabs.pinned.selected.odd.fg = "#a0b3c5"
c.colors.tabs.pinned.selected.odd.bg = "#41505e"
c.colors.tabs.pinned.selected.even.fg = "#a0b3c5"
c.colors.tabs.pinned.selected.even.bg = "#41505e"

# Bindings for normal mode

c.colors.webpage.darkmode.enabled = True
config.bind(";;", "set downloads.location.directory ~/Downloads ;; hint links download")
config.bind(";D", "set downloads.location.directory ~/Downloads ;; hint images download")
config.bind("<Ctrl+o>", "open --private")
