live_config_reload = true

#[env]
#TERM = "xterm-256color"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
dynamic_title = true
opacity = 0.75
startup_mode = "Windowed"
title = "Alacritty"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0

[window.position]
x = 0
y = 0

[terminal]
shell = { program = "powershell.exe", args = [
  "-NoExit",
  "-Command",
  "&{Import-Module \"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\Tools\\Microsoft.VisualStudio.DevShell.dll\"; Enter-VsDevShell 8b68ffab -SkipAutomaticLocation -DevCmdArguments \"-arch=x64 -host_arch=x64\"}; nu.exe",
] }
