hl.on("hyprland.start", function ()
  hl.exec_cmd("kanshi")
  hl.exec_cmd("awww-daemon --format xrgb")
  hl.exec_cmd("fcitx5 -d")
  hl.exec_cmd("vicinae server")
  hl.exec_cmd("nm-applet --indicator")
  hl.exec_cmd("synology-drive")
  hl.exec_cmd("wl-paste --type text --watch cliphist store")
  hl.exec_cmd("wl-paste --type image --watch cliphist store")
  hl.exec_cmd("systemctl --user import-environment && systemctl --user start linux-id.service")
  hl.exec_cmd("hash dbus-update-activation-environment 2>/dev/null")
  hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP PATH")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("noctalia")
end)
