# Copyright (C) 2025 Sungbae Jeong
# Based on https://github.com/Keyitdev/sddm-astronaut-theme
# Distributed under the GPLv3+ License https://www.gnu.org/licenses/gpl-3.0.html

[General]
ScreenWidth="3200"
ScreenHeight="2000"
ScreenPadding=""
Font="pixelon"
FontSize="25"
KeyboardSize="0.6"
RoundCorners="20"
Locale=""
HourFormat="HH:mm"
DateFormat="dddd d"
HeaderText=""

BackgroundPlaceholder="moon-cat.png"
Background="moon-cat.mp4"
BackgroundSpeed="1.0"
PauseBackground=""
DimBackground="0.0"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

HeaderTextColor="#c1becd"
DateTextColor="#c1becd"
TimeTextColor="#c1becd"

FormBackgroundColor="#242455"
BackgroundColor="#242455"
DimBackgroundColor="#242455"

LoginFieldBackgroundColor="#111111"
PasswordFieldBackgroundColor="#111111"
LoginFieldTextColor="#c1becd"
PasswordFieldTextColor="#c1becd"
UserIconColor="#c1becd"
PasswordIconColor="#c1becd"

PlaceholderTextColor="#bbbbbb"
WarningColor="#c1becd"

LoginButtonTextColor="#000055"
LoginButtonBackgroundColor="#c1becd"
SystemButtonsIconsColor="#c1becd"
SessionButtonTextColor="#c1becd"
VirtualKeyboardButtonTextColor="#c1becd"

DropdownTextColor="#000055"
DropdownSelectedBackgroundColor="#c1becd"
DropdownBackgroundColor="#90b4ff"

HighlightTextColor="#000055"
HighlightBackgroundColor="#c1becd"
HighlightBorderColor="transparent"

HoverUserIconColor="#fcfcff"
HoverPasswordIconColor="#fcfcff"
HoverSystemButtonsIconsColor="#fcfcff"
HoverSessionButtonTextColor="#fcfcff"
HoverVirtualKeyboardButtonTextColor="#fcfcff"

PartialBlur="true"
FullBlur=""
BlurMax="8"
Blur="2.0"
HaveFormBackground="true"
FormPosition="left"

VirtualKeyboardPosition="right"

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"
ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"

TranslatePlaceholderUsername=""
TranslatePlaceholderPassword=""
TranslateLogin=""
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateSessionSelection=""
TranslateVirtualKeyboardButtonOn=""
TranslateVirtualKeyboardButtonOff=""

